services:
  web:
    container_name: web-notebook
    build:
      context: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
      - db

  app:
    container_name: app-notebook
    build:
      context: ./docker/app/
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html/
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
      - ./docker/app/php.ini:/etc/php.ini
  db:
    container_name: pgdb-notebook
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdb-notebook-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdb-notebook-volume: